INSERT INTO country (name)
VALUES ('Cyprus'),
('Czech Republic'),
('Denmark'),
('Estonia'),
('Finland'),
('France'),
('Greece'),
('Hungary'),
('Ireland'),
('Italy'),
('Latvia'),
('Lithuania'),
('Luxembourg'),
('Netherlands'),
('Norway'),
('Poland'),
('Portugal'),
('Romania'),
('Slovakia'),
('Slovenia'),
('Spain'),
('Sweden'),
('Switzerland'),
('United Kingdom');
